apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  nodeName: i-0811756c48c3b95f9  # Replace with actual node name
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: html-volume
      hostPath:
        path: /mnt/data/
        type: DirectoryOrCreate

