kind: Pod
apiVersion: v1
metadata:
  name: project
  labels:
    name: project
    env: dev
spec:
  containers:
  - name: frontend
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

